---
output: github_document
always_allow_html: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r Setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# datavolleyXtra

<!-- badges: start -->

<!-- badges: end -->

datavolleyXtra is a supplementary to <https://github.com/openvolley/datavolley>.

-   Parsing additions

-   Tables

-   Plots

## Installation

You can install the development version of datavolleyXtra from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("tyler-widdison/datavolleyXtra")
```

## Reading datavolley files

```{r FileReading}
library(datavolleyXtra)
df <- dv_readXtra("dvws")
```

------------------------------------------------------------------------

#### Additions

-   set_player

-   Player

-   opponent

-   reception_quality

-   dig_quality

-   setter_position

-   filename

-   date

-   dashboards

-   plots

-   \+ more!

------------------------------------------------------------------------


## Dashboards 

### Rotation rec table

```{r ReceptionTable}
rec_app(df)
```

